#!/bin/sh
##
# camserver
# Author: RenêS. Pinto
#

VIDEODEV=/dev/video0

v4l2-ctl -d $VIDEODEV --set-input 1 --set-standard=pal-m

VELEM="v4l2src device=$VIDEODEV"
#VCAPS="video/x-raw-yuv,format=(fourcc)YUY2,width=320,height=240"
#TIME="timeoverlay halign=right valign=top !"
CLOCK="clockoverlay halign=right valign=top shaded-background=true time-format=\"%d/%m/%Y %H:%M:%S\""
VSOURCE="$VELEM ! $CLOCK"

#STREAM="ffmpegcolorspace ! videoscale ! video/x-raw-yuv,width=320,height=240 ! theoraenc quality=16 ! oggmux ! shout2send ip=10.1.1.1 port=8000 password=ajc521 mount=live.ogg"

STREAM="ffmpegcolorspace ! videoscale video/x-raw-yuv,width=512,height=384 ! theoraenc quality=16 ! oggmux ! shout2send ip=10.1.1.1 port=8000 password=ajc521 mount=live.ogg"


PIPELINE="$VSOURCE ! $STREAM"

GST_LAUNCH=$(which gst-launch-0.10)
if [ -n "$GST_LAUNCH" ]; then
	$GST_LAUNCH -v $PIPELINE
fi

